import { ScrollCompressorMeasurements, ScrollCompressorResult, ScrollCompressorValues, ScrollCompressorFlags, ScrollCompressorConfig } from './scroll.types';
import { DiagnosticStatus, Recommendation, round } from '../../shared/wshp.types';

// Phase 3.4: Physics Kernel imports
import { computeCompressionRatio } from '../../physics/hvac';
import { computePercentRLA } from '../../physics/electrical';

function analyzeCompressionRatio(ratio: number) {
  if (ratio < 2.5) return { status: 'critical' as DiagnosticStatus };
  if (ratio < 3.0) return { status: 'alert' as DiagnosticStatus };
  if (ratio > 6.0) return { status: 'alert' as DiagnosticStatus };
  if (ratio > 8.0) return { status: 'critical' as DiagnosticStatus };
  return { status: 'ok' as DiagnosticStatus };
}

function analyzeCurrent(current: number | undefined, rla: number | undefined) {
  if (current === undefined || rla === undefined) return { status: 'ok' as DiagnosticStatus };
  // Phase 3.4: Use kernel for percent RLA calculation
  const pct = computePercentRLA(current, rla);
  if (pct > 1.3) return { status: 'critical' as DiagnosticStatus };
  if (pct > 1.1) return { status: 'alert' as DiagnosticStatus };
  if (pct < 0.4) return { status: 'warning' as DiagnosticStatus };
  return { status: 'ok' as DiagnosticStatus };
}

export function generateScrollRecommendations(
  compAnalysis: { status: DiagnosticStatus },
  currentAnalysis: { status: DiagnosticStatus },
  measurements: ScrollCompressorMeasurements
): Recommendation[] {
  const recommendations: Recommendation[] = [];
  if (compAnalysis.status !== 'ok') {
    recommendations.push({
      id: 'compressor_scroll_compression_ratio_issue',
      domain: 'compressor_scroll',
      severity: compAnalysis.status === 'critical' ? 'critical' : 'alert',
      intent: 'diagnostic',
      summary: `Compression ratio ${round(measurements.dischargePressure / measurements.suctionPressure, 2)}:1 is outside expected range.`,
      rationale: 'Compression ratio flagged outside expected range; further diagnostic evaluation is recommended.',
      notes: [`Compression ratio: ${round(measurements.dischargePressure / measurements.suctionPressure, 2)}:1`],
      requiresShutdown: compAnalysis.status === 'critical',
    });
  }
  if (currentAnalysis.status !== 'ok') {
    recommendations.push({
      id: 'compressor_scroll_current_issue',
      domain: 'compressor_scroll',
      severity: currentAnalysis.status === 'critical' ? 'critical' : 'alert',
      intent: 'diagnostic',
      summary: measurements.runningCurrent !== undefined ? `Measured current ${round(measurements.runningCurrent, 1)} A is outside expected range.` : 'Measured current outside expected range.',
      rationale: 'Electrical or mechanical loading issue suspected; verify motor and circuit conditions.',
      notes: measurements.runningCurrent !== undefined ? [`Measured current ${round(measurements.runningCurrent, 1)} A`] : [],
      requiresShutdown: currentAnalysis.status === 'critical',
    });
  }
  if (recommendations.length === 0) {
    recommendations.push({
      id: 'compressor_scroll_no_immediate_action',
      domain: 'compressor_scroll',
      severity: 'info',
      intent: 'diagnostic',
      summary: 'Compressor within normal parameters — continue routine monitoring.',
      rationale: 'No abnormal compressor compression or current detected.',
      notes: ['Compressor within normal parameters.'],
      requiresShutdown: false,
    });
  }
  return recommendations;
}

export function runScrollCompressorEngine(measurements: ScrollCompressorMeasurements, profile: ScrollCompressorConfig): ScrollCompressorResult {
  const disclaimers: string[] = [];
  // Build simple analysis
  const suction = measurements.suctionPressure;
  const discharge = measurements.dischargePressure;

  // Phase 3.4: Use kernel for compression ratio calculation
  const compressionRatio = computeCompressionRatio(discharge, suction);

  const compAnalysis = analyzeCompressionRatio(compressionRatio);

  // read only shallow, well-known profile fields (avoid deep, appliance-specific config)
  const rla = profile?.compressor?.rla;
  const currentAnalysis = analyzeCurrent(measurements.runningCurrent, rla);

  // Consolidate overall status
  const statuses = [compAnalysis.status, currentAnalysis.status];
  const worst = statuses.includes('critical') ? 'critical' : statuses.includes('alert') ? 'alert' : statuses.includes('warning') ? 'warning' : 'ok';

  // presentation-level overallFinding/likelyIssue are generated by modules/UI; engines remain text-free

  const recommendations = generateScrollRecommendations(compAnalysis, currentAnalysis, measurements);

  // Add a small protective disclaimer about manufacturer-specific compressors (medical custom refrigerants)
  // Record a small protective disclaimer for custom refrigerants — prefer the canonical field `refrigerantType`.
  const refrigerantFromProfile = profile?.refrigeration?.refrigerantType;
  if (profile?.compressor?.type === 'scroll' && profile?.model && String(refrigerantFromProfile || '').toUpperCase() === 'OTHER') {
    disclaimers.push('Using "OTHER" refrigerant — verify compressor performance and curves with the equipment manufacturer and IOM manual. Custom refrigerants may change performance and limits.');
  }

  const values: ScrollCompressorValues = {
    suctionPressure: suction,
    dischargePressure: discharge,
    compressionRatio: round(compressionRatio, 2),
    currentDraw: measurements.runningCurrent,
  };

  const flags: ScrollCompressorFlags = {
    currentStatus: currentAnalysis.status,
    compressionStatus: compAnalysis.status,
    disclaimers,
  };

  return {
    status: worst as DiagnosticStatus,
    values,
    flags,
    recommendations,
    // Backward-compatible flattened fields
    compressorType: 'scroll',
    suctionPressure: values.suctionPressure,
    dischargePressure: values.dischargePressure,
    compressionRatio: values.compressionRatio,
    compressionStatus: flags.compressionStatus,
    currentDraw: values.currentDraw,
    currentStatus: flags.currentStatus,
    disclaimers: flags.disclaimers,
  };
}
